### ISSUE TITLE
到拼图的部分就找不到元素了。

### ISSUE THREAD

**Issue by levie-vans** [QvQQ/ChatGPT-Register#1]
INFO     Got the verification mail for flying_mudfish@zhitong.work!
                    INFO     检查认证链接是否存在: flying_mudfish@zhitong.work - 存在
                    INFO     已获取到账号的认证链接！
                    INFO     Waiting for monitoring thread to end...
2024/01/10 08:43:51 INFO     All emails have been checked.
2024/01/10 08:43:53 INFO     Monitoring thread ended.
                    INFO     Waiting for verify button appears...
                    INFO     Waiting for link textarea appears...
                    INFO     Inputting verify link...
                    INFO     Looking for OK button to click...
2024/01/10 08:43:54 INFO     Verify link submitted.
                    INFO     Waiting for username input appears...
2024/01/10 08:43:57 INFO     Inputting username...
                    INFO     Looking for continue button to click...
                    INFO     Username submitted.
                    INFO     Waiting for puzzle to be solved...
                    INFO     Waiting for puzzle button appears...
2024/01/10 08:45:33 ERROR    Element //button is not found.
Traceback (most recent call last):
  File "/opt/ChatGPT-Register/main.py", line 1003, in <module>
    register.wait_for_puzzle(question_type=puzzle_type)
  File "/opt/ChatGPT-Register/main.py", line 227, in wait_for_puzzle
    self.solver.solve(question_type)
  File "/opt/ChatGPT-Register/main.py", line 525, in solve
    puzzle_button = self.helper.sleepy_find_element(By.XPATH, "//button[text()='开始拼图' or text()='再次尝试']")
  File "/opt/ChatGPT-Register/main.py", line 827, in sleepy_find_element
    raise Exceptions.NoSuchElementException(f'Element {query} is not found.')
selenium.common.exceptions.NoSuchElementException: Message: Element //button[text()='开始拼图' or text()='再次尝试'] is not found.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception

**Comment by QvQQ** [comment]
headless设为false看看什么情况

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: levie-vans ***@***.***>
发送时间: Wednesday, January 10, 2024 4:51:46 PM
收件人: QvQQ/ChatGPT-Register ***@***.***>
抄送: Subscribed ***@***.***>
主题: [QvQQ/ChatGPT-Register] 到拼图的部分就找不到元素了。 (Issue #1)


                INFO     Got the verification mail for ***@***.***!
                INFO     检查认证链接是否存在: ***@***.*** - 存在
                INFO     已获取到账号的认证链接！
                INFO     Waiting for monitoring thread to end...


2024/01/10 08:43:51 INFO All emails have been checked.
2024/01/10 08:43:53 INFO Monitoring thread ended.
INFO Waiting for verify button appears...
INFO Waiting for link textarea appears...
INFO Inputting verify link...
INFO Looking for OK button to click...
2024/01/10 08:43:54 INFO Verify link submitted.
INFO Waiting for username input appears...
2024/01/10 08:43:57 INFO Inputting username...
INFO Looking for continue button to click...
INFO Username submitted.
INFO Waiting for puzzle to be solved...
INFO Waiting for puzzle button appears...
2024/01/10 08:45:33 ERROR Element //button is not found.
Traceback (most recent call last):
File "/opt/ChatGPT-Register/main.py", line 1003, in
register.wait_for_puzzle(question_type=puzzle_type)
File "/opt/ChatGPT-Register/main.py", line 227, in wait_for_puzzle
self.solver.solve(question_type)
File "/opt/ChatGPT-Register/main.py", line 525, in solve
puzzle_button = self.helper.sleepy_find_element(By.XPATH, "//button[text()='开始拼图' or text()='再次尝试']")
File "/opt/ChatGPT-Register/main.py", line 827, in sleepy_find_element
raise Exceptions.NoSuchElementException(f'Element {query} is not found.')
selenium.common.exceptions.NoSuchElementException: Message: Element //button[text()='开始拼图' or text()='再次尝试'] is not found.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception

―

**Comment by levie-vans** [comment]
因为是Ubuntu的服务器，设为false的话，一直卡在这里：
python3 main.py
2024/01/10 11:19:14 INFO     Loading undetected Chrome

**Comment by levie-vans** [comment]
而使用Docker的话，验证码无论如何也过不了，已经根据图片换了对应的验证码类型。

**Comment by levie-vans** [comment]
现在换错误了：
``` 
检查认证链接是否存在: chief_pangolin@xxxxx.wiki - 存在
                    INFO     已获取到账号的认证链接！
                    INFO     Waiting for monitoring thread to end...
2024/01/10 11:22:57 INFO     All emails have been checked.
2024/01/10 11:22:59 INFO     Monitoring thread ended.
                    INFO     Waiting for verify button appears...
                    INFO     Waiting for link textarea appears...
                    INFO     Inputting verify link...
2024/01/10 11:23:00 INFO     Looking for OK button to click...
                    INFO     Verify link submitted.
                    INFO     Waiting for username input appears...
2024/01/10 11:23:04 INFO     Inputting username...
                    INFO     Looking for continue button to click...
Traceback (most recent call last):
  File "/opt/ChatGPT-Register/main.py", line 1000, in <module>
    register.input_username(email.split('@')[0])
  File "/opt/ChatGPT-Register/main.py", line 251, in input_username
    continue_button.click()
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button type="submit" name="action" value="default" class="c14249a2a c73baee07 c9c27edbd c58b4df90 _button-login-password" data-action-button-primary="true" disabled="">...</button> is not clickable at point (350, 523). Other element would receive the click: <div class="cc6121580">...</div>
  (Session info: chrome=120.0.6099.216)
Stacktrace:
#0 0x55eff8966f83 <unknown>
#1 0x55eff861fcf7 <unknown>
#2 0x55eff8677d92 <unknown>
#3 0x55eff86757f4 <unknown>
#4 0x55eff8672894 <unknown>
#5 0x55eff86714b9 <unknown>
#6 0x55eff8663313 <unknown>
#7 0x55eff86990b2 <unknown>
#8 0x55eff8662b49 <unknown>
#9 0x55eff86994ce <unknown>
#10 0x55eff86b8006 <unknown>
#11 0x55eff8698e53 <unknown>
#12 0x55eff8660dd4 <unknown>
#13 0x55eff86621de <unknown>
#14 0x55eff892b531 <unknown>
#15 0x55eff892f455 <unknown>
#16 0x55eff8917f55 <unknown>
#17 0x55eff89300ef <unknown>
#18 0x55eff88fb99f <unknown>
#19 0x55eff8954008 <unknown>
#20 0x55eff89541d7 <unknown>
#21 0x55eff8966124 <unknown>
#22 0x7f0eb43f7ac3 <unknown>
```
